# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.database_name = QtWidgets.QLabel(self.centralwidget)
        self.database_name.setGeometry(QtCore.QRect(20, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.database_name.setFont(font)
        self.database_name.setObjectName("database_name")
        self.collection_name = QtWidgets.QLabel(self.centralwidget)
        self.collection_name.setGeometry(QtCore.QRect(20, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.collection_name.setFont(font)
        self.collection_name.setObjectName("collection_name")
        self.startPoint = QtWidgets.QLabel(self.centralwidget)
        self.startPoint.setGeometry(QtCore.QRect(20, 130, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.startPoint.setFont(font)
        self.startPoint.setObjectName("startPoint")
        self.stopPoint = QtWidgets.QLabel(self.centralwidget)
        self.stopPoint.setGeometry(QtCore.QRect(20, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.stopPoint.setFont(font)
        self.stopPoint.setObjectName("stopPoint")
        self.databaseEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.databaseEdit.setGeometry(QtCore.QRect(140, 30, 341, 31))
        self.databaseEdit.setObjectName("databaseEdit")
        self.stopPointEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.stopPointEdit.setGeometry(QtCore.QRect(90, 200, 341, 31))
        self.stopPointEdit.setObjectName("stopPointEdit")
        self.startPointEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.startPointEdit.setGeometry(QtCore.QRect(90, 140, 341, 31))
        self.startPointEdit.setObjectName("startPointEdit")
        self.collectionEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.collectionEdit.setGeometry(QtCore.QRect(140, 80, 341, 31))
        self.collectionEdit.setObjectName("collectionEdit")
        self.outputEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.outputEdit.setGeometry(QtCore.QRect(120, 270, 521, 41))
        self.outputEdit.setObjectName("outputEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 270, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.countButton = QtWidgets.QPushButton(self.centralwidget)
        self.countButton.setGeometry(QtCore.QRect(540, 80, 81, 31))
        self.countButton.setObjectName("countButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MongoDB Client"))
        self.database_name.setText(_translate("MainWindow", "Database:"))
        self.collection_name.setText(_translate("MainWindow", "Collection:"))
        self.startPoint.setText(_translate("MainWindow", "Start:"))
        self.stopPoint.setText(_translate("MainWindow", "Stop:"))
        self.label.setText(_translate("MainWindow", "Output"))
        self.countButton.setText(_translate("MainWindow", "Count"))
