# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow,  QAction, QTextEdit
from PyQt5.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 21))
        self.fileMenu = self.menubar.addMenu('File')
        self.editMenu = self.menubar.addMenu('Edit')
        self.viewMenu = self.menubar.addMenu('View')
        self.helpMenu = self.menubar.addMenu('Help')
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.copyAction = QAction(QIcon("Resources/copy.png"), 'Copy')
        self.copyAction.setShortcut("Ctrl+C")
        self.fileMenu.addAction(self.copyAction)
        self.saveAction = QAction(QIcon("Resources/save.png"), 'Save')
        self.saveAction.setShortcut("Ctrl+S")
        self.fileMenu.addAction(self.saveAction)
        self.pasteAction = QAction(QIcon("Resources/paste.jpg"), 'Paste')
        self.pasteAction.setShortcut("Ctrl+P")
        self.fileMenu.addAction(self.pasteAction)
        self.exiteAction = QAction(QIcon("Resources/new.jpg"), 'Exit')
        self.exiteAction.setShortcut("Ctrl+E")
        self.exiteAction.triggered.connect(self.exitWindow)
        self.fileMenu.addAction(self.exiteAction)
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.addAction(self.copyAction)
        self.toolbar.addAction(self.saveAction)
        self.toolbar.addAction(self.pasteAction)
        self.toolbar.addAction(self.exiteAction)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileMenu.setWindowTitle(_translate("MainWindow", "File"))
        self.editMenu.setWindowTitle(_translate("MainWindow", "Edit"))
        self.helpMenu.setWindowTitle(_translate("MainWindow", "Help"))
        self.viewMenu.setWindowTitle(_translate("MainWindow", "View"))

    def exitWindow(self):
        self.close()

    def createEditor(self):
        self.textEdit = QTextEdit(self)
        self.setCentralWidget(self.textEdit)
